create extension if not exists moddatetime schema extensions;

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  documento text not null,
  question_number integer not null,
  pregunta text not null,
  opciones jsonb not null,
  review_status text not null default 'pending' check (review_status in ('published', 'pending', 'needs_review')),
  is_active boolean not null default true,
  editor_note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists questions_documento_question_number_idx
  on public.questions (documento, question_number);

create index if not exists questions_review_status_idx
  on public.questions (review_status);

create index if not exists questions_is_active_idx
  on public.questions (is_active);

create table if not exists public.question_reports (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  note text not null,
  status text not null default 'new' check (status in ('new', 'reviewing', 'resolved', 'dismissed')),
  question_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists question_reports_question_id_idx
  on public.question_reports (question_id);

create index if not exists question_reports_status_idx
  on public.question_reports (status);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_questions_updated_at on public.questions;
create trigger trg_questions_updated_at
before update on public.questions
for each row
execute function public.set_updated_at();

alter table public.questions enable row level security;
alter table public.question_reports enable row level security;

drop policy if exists "public can read active questions" on public.questions;
create policy "public can read active questions"
on public.questions
for select
using (is_active = true);

drop policy if exists "authenticated can manage questions" on public.questions;
create policy "authenticated can manage questions"
on public.questions
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "public can create reports" on public.question_reports;
create policy "public can create reports"
on public.question_reports
for insert
with check (true);

drop policy if exists "authenticated can read reports" on public.question_reports;
create policy "authenticated can read reports"
on public.question_reports
for select
using (auth.role() = 'authenticated');

drop policy if exists "authenticated can update reports" on public.question_reports;
create policy "authenticated can update reports"
on public.question_reports
for update
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');
